# Generated by Django 4.1.5 on 2023-03-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sentences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qus', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='speech_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=1000)),
                ('para', models.CharField(max_length=1000)),
                ('not_recognized_words', models.CharField(max_length=1000)),
                ('progress', models.CharField(max_length=100)),
            ],
        ),
    ]
